### ISSUE TITLE
rosdep install error

### ISSUE THREAD

**Issue by hj2222** [msadowski/x2_cartographer#1]
when i run "rosdep install --from-paths src --ignore-src --rosdistro melodic -r -y"

i got these errors, could u help me?

ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y ros-melodic-cartographer] failed
  apt: Failed to detect successful installation of [ros-melodic-cartographer]

**Comment by msadowski** [comment]
Hi!

Sorry for a late reply. Try to install cartographer manually. On melodic you should be able to do:
`sudo apt-get install ros-melodic-cartographer`.

If this doesn't work you will need to follow Cartographer's docs for installing it manually: https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html#building-installation

Let me know if that worked!

**Comment by hj2222** [comment]
after this command 'install' ros ~, 'catkin_make' does not need?
